// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeifDigital.Data;

#nullable disable

namespace SeifDigital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327_AddUserNoteEncryption")]
    partial class AddUserNoteEncryption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Entity UserNote
            modelBuilder.Entity("SeifDigital.Models.UserNote", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("OwnerKey")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("OwnerUser")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("TextCriptat")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("OwnerKey");

                b.ToTable("UserNote");
            });
#pragma warning restore 612, 618
        }
    }
}
