// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeifDigital.Data;

#nullable disable

namespace SeifDigital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430141128_AddOriginServerVerificationFieldsToManagedCertificates")]
    partial class AddOriginServerVerificationFieldsToManagedCertificates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeifDigital.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ValueString")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorSid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTimeUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.InformatieFisier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InformatieSensibila_Id")
                        .HasColumnType("int");

                    b.Property<long>("UserFile_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InformatieSensibila_Id");

                    b.HasIndex("UserFile_Id");

                    b.HasIndex("InformatieSensibila_Id", "UserFile_Id");

                    b.ToTable("InformatieFisier", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.InformatieImagine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("InformatieSensibila_Id")
                        .HasColumnType("int");

                    b.Property<long>("UserFile_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InformatieSensibila_Id");

                    b.HasIndex("UserFile_Id");

                    b.HasIndex("InformatieSensibila_Id", "UserFile_Id");

                    b.ToTable("InformatieImagine", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.InformatieSensibila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateCriptate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetaliiCriptate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetaliiTokens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NumeUtilizator")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitluAplicatie")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UsernameSalvat")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKey");

                    b.ToTable("InformatiiSensibile", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.ManagedCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CertificateExpiryDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CertificateIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CertificateSubject")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DaysUntilExpiry")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsCertificateMismatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastCheckDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("OriginCertificateExpiryDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OriginCertificateIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OriginCertificateSubject")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("OriginDaysUntilExpiry")
                        .HasColumnType("int");

                    b.Property<string>("OriginServerIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("OriginServerPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(443);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.ToTable("ManagedCertificates", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.NoteFisier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserFile_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("UserNote_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserFile_Id");

                    b.HasIndex("UserNote_Id");

                    b.HasIndex("UserNote_Id", "UserFile_Id");

                    b.ToTable("NoteFisier", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccount", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.UserFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoredRelativePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserFile", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.UserMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachedImageFileIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DateCriptate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetaliiCriptate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetaliiTokens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("OriginalId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecipientOwnerKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("SavedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Text")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TitluAplicatie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsernameSalvat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientOwnerKey");

                    b.HasIndex("SourceType");

                    b.ToTable("UserMessage", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.UserNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OwnerKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("OwnerKey");

                    b.Property<string>("OwnerUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("OwnerUser");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NoteText");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKey");

                    b.ToTable("UserNote", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DomainUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastVerifiedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DomainUser")
                        .IsUnique();

                    b.ToTable("UserProfile", "dbo");
                });

            modelBuilder.Entity("SeifDigital.Models.InformatieFisier", b =>
                {
                    b.HasOne("SeifDigital.Models.InformatieSensibila", "InformatieSensibila")
                        .WithMany("Fisieri")
                        .HasForeignKey("InformatieSensibila_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeifDigital.Models.UserFile", "UserFile")
                        .WithMany("InformatiiSensibile")
                        .HasForeignKey("UserFile_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformatieSensibila");

                    b.Navigation("UserFile");
                });

            modelBuilder.Entity("SeifDigital.Models.InformatieImagine", b =>
                {
                    b.HasOne("SeifDigital.Models.InformatieSensibila", "InformatieSensibila")
                        .WithMany()
                        .HasForeignKey("InformatieSensibila_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeifDigital.Models.UserFile", "UserFile")
                        .WithMany()
                        .HasForeignKey("UserFile_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformatieSensibila");

                    b.Navigation("UserFile");
                });

            modelBuilder.Entity("SeifDigital.Models.NoteFisier", b =>
                {
                    b.HasOne("SeifDigital.Models.UserFile", "UserFile")
                        .WithMany()
                        .HasForeignKey("UserFile_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeifDigital.Models.UserNote", "UserNote")
                        .WithMany("Fisieri")
                        .HasForeignKey("UserNote_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFile");

                    b.Navigation("UserNote");
                });

            modelBuilder.Entity("SeifDigital.Models.InformatieSensibila", b =>
                {
                    b.Navigation("Fisieri");
                });

            modelBuilder.Entity("SeifDigital.Models.UserFile", b =>
                {
                    b.Navigation("InformatiiSensibile");
                });

            modelBuilder.Entity("SeifDigital.Models.UserNote", b =>
                {
                    b.Navigation("Fisieri");
                });
#pragma warning restore 612, 618
        }
    }
}
